# Generated by Django 2.1.7 on 2019-11-28 00:50

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='陕-', max_length=20, verbose_name='车号')),
                ('image', models.ImageField(default='', upload_to='clgl/bus', verbose_name='图片')),
                ('desc', DjangoUeditor.models.UEditorField(default='', verbose_name='车辆简历')),
                ('xsz', models.CharField(max_length=20, verbose_name='行驶证 ')),
                ('yyz', models.CharField(max_length=20, verbose_name='营运证 ')),
                ('rh_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='入户时间')),
                ('lxdj', models.CharField(choices=[('0', '中型中级'), ('1', '小型中级'), ('2', '高一级')], max_length=1, verbose_name='类型等级')),
                ('is_sy', models.BooleanField(default='true', verbose_name='是否审验')),
                ('bm', models.CharField(choices=[('0', '客运队'), ('1', '公交公司')], default='0', max_length=1, verbose_name='管理部门')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '车辆',
                'verbose_name_plural': '车辆',
            },
        ),
        migrations.CreateModel(
            name='Bus_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('bm', models.CharField(choices=[('0', '客运队'), ('1', '公交公司')], default=0, max_length=1, verbose_name='所属部门')),
                ('sfz', models.CharField(blank=True, max_length=18, null=True, verbose_name='身份证')),
                ('pic', models.ImageField(default='', upload_to='clgl/user/sfz/', verbose_name='照片')),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='0', max_length=1, verbose_name='性别')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='简历')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('cb_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='经营时间')),
                ('fujian', models.ImageField(default='', upload_to='clgl/user/fj/', verbose_name='承包附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '经营人管理',
                'verbose_name_plural': '经营人管理',
            },
        ),
        migrations.CreateModel(
            name='Jsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('bm', models.CharField(choices=[('0', '客运队'), ('1', '公交公司')], default=0, max_length=1, verbose_name='所属部门')),
                ('jsz', models.CharField(max_length=18, verbose_name='驾驶证')),
                ('zgz', models.CharField(blank=True, max_length=20, null=True, verbose_name='资格证')),
                ('image', models.ImageField(default='', upload_to='clgl/jsz/', verbose_name='驾驶证')),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='0', max_length=1, verbose_name='性别')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='简历')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('cj_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='参加工作时间')),
                ('work_years', models.IntegerField(blank=True, default=0, null=True, verbose_name='工作年限')),
                ('is_zg', models.BooleanField(default='true', verbose_name='是否在岗')),
                ('age', models.IntegerField(blank=True, default=18, null=True, verbose_name='年龄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '驾驶员管理',
                'verbose_name_plural': '驾驶员管理',
            },
        ),
        migrations.CreateModel(
            name='Spy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('bm', models.CharField(choices=[('0', '客运队'), ('1', '公交公司')], default=0, max_length=1, verbose_name='所属部门')),
                ('sfz', models.CharField(max_length=18, verbose_name='身份证')),
                ('sgz', models.CharField(blank=True, max_length=10, null=True, verbose_name='上岗证')),
                ('image', models.ImageField(default='', upload_to='clgl/spy/', verbose_name='照片')),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='1', max_length=1, verbose_name='性别')),
                ('detail', DjangoUeditor.models.UEditorField(default='', verbose_name='简历')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('cj_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='参加工作时间')),
                ('work_years', models.IntegerField(blank=True, default=0, null=True, verbose_name='工作年限')),
                ('is_zg', models.BooleanField(default='true', verbose_name='是否在岗')),
                ('age', models.IntegerField(blank=True, default=18, null=True, verbose_name='年龄')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '售票员管理',
                'verbose_name_plural': '售票员管理',
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clgl.Bus_user', verbose_name='经营人'),
        ),
        migrations.AddField(
            model_name='bus',
            name='jsy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clgl.Jsy', verbose_name='驾驶员'),
        ),
        migrations.AddField(
            model_name='bus',
            name='spy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clgl.Spy', verbose_name='售票员'),
        ),
    ]
