# Generated by Django 2.1.7 on 2019-12-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgl', '0002_auto_20191128_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_user',
            name='fujian',
            field=models.FileField(default='', upload_to='clgl/user/fj/', verbose_name='承包附件'),
        ),
    ]
