# Generated by Django 2.1.7 on 2019-11-22 03:37

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='部门')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Yg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('sfz', models.CharField(blank=True, default='612322', max_length=18, null=True, verbose_name='身份证')),
                ('sfz_img', models.ImageField(blank=True, max_length=255, null=True, upload_to='yg', verbose_name='身份证图片')),
                ('gender', models.CharField(choices=[('0', '男'), ('1', '女')], default='0', max_length=1, verbose_name='性别')),
                ('address', models.CharField(default='', max_length=100, verbose_name='地址')),
                ('desc', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='简历')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机')),
                ('is_zg', models.BooleanField(default='true', verbose_name='是否在岗')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('bm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yggl.Bm', verbose_name='部门')),
            ],
            options={
                'verbose_name': '姓名',
                'verbose_name_plural': '姓名',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='YgCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=25, verbose_name='员工类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.CreateModel(
            name='YgTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=25, verbose_name='标签名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='yg',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yggl.YgCategory', verbose_name='人员类别'),
        ),
        migrations.AddField(
            model_name='yg',
            name='tags',
            field=models.ManyToManyField(to='yggl.YgTag', verbose_name='标签'),
        ),
    ]
